platform :ios, '9.0'
use_frameworks!

def standard_pods
  pod 'LabelConfigurator', :path => '../'
end

target 'LabelConfigurator_Example' do
  standard_pods
end

target 'LabelConfigurator_Tests' do
  standard_pods
end
