platform :ios, '9.0'
use_frameworks!

target 'LabelConfigurator_Example' do
  pod 'LabelConfigurator', :path => '../'

  target 'LabelConfigurator_Tests' do
    inherit! :search_paths

#pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
